FROM postgres:12 

RUN mkdir /var/lib/postgresql/data/decoderbufs
RUN chown -R postgres:postgres /var/lib/postgresql/data/decoderbufs \
    && chmod -R 700 /var/lib/postgresql/data/decoderbufs

# COPY postgresql.conf.sample /usr/share/postgresql/postgresql.conf.sample

COPY migrations/init/ /docker-entrypoint-initdb.d/7