FROM redis AS redis-master
# Create foder

RUN apt-get update && apt-get install logrotate -y \ 
    && chmod +x /usr/local/bin/scrip/scrip_redis.sh \
        && chown root:root /usr/local/bin/scrip \
            && chmod 755 /usr/local/bin/scrip

