import {
  CalenderIcon,
  CharFillIcon,
  ChartIcon,
  FolderIcon,
  SearchIcon,
  SettingIcon,
  UserIcon,
} from '../imports/home_import/index';

export const allLanguageOption = [
  { value: 'Afrikaans', label: 'Afrikaans' },
  { value: 'Albanian', label: 'Albanian - shqip' },
  { value: 'Amharic', label: 'Amharic - አማርኛ' },
  { value: 'Arabic', label: 'Arabic - العربية' },
  { value: 'Aragonese', label: 'Aragonese - aragonés' },
  { value: 'Armenian', label: 'Armenian - հայերեն' },
  { value: 'Asturian', label: 'Asturian - asturianu' },
  { value: 'Azerbaijani', label: 'Azerbaijani - azərbaycan dili' },
  { value: 'Basque', label: 'Basque - euskara' },
  { value: 'Belarusian', label: 'Belarusian - беларуская' },
  { value: 'Bengali', label: 'Bengali - বাংলা' },
  { value: 'Bosnian', label: 'Bosnian - bosanski' },
  { value: 'Breton', label: 'Breton - brezhoneg' },
  { value: 'Bulgarian', label: 'Bulgarian - български' },
  { value: 'Catalan', label: 'Catalan - català' },
  { value: 'Central Kurdish', label: 'Central Kurdish - کوردی (دەستنوسی عەرەبی)' },
  { value: 'Chinese', label: 'Chinese - 中文' },
  { value: 'Chinese (Hong Kong)', label: 'Chinese (Hong Kong) - 中文（香港）' },
  { value: 'Chinese (Simplified)', label: 'Chinese (Simplified) - 中文（简体）' },
  { value: 'Chinese (Traditional)', label: 'Chinese (Traditional) - 中文（繁體）' },
  { value: 'Corsican', label: 'Corsican' },
  { value: 'Croatian', label: 'Croatian - hrvatski' },
  { value: 'Czech', label: 'Czech - čeština' },
  { value: 'Danish', label: 'Danish - dansk' },
  { value: 'Dutch', label: 'Dutch - Nederlands' },
  { value: 'English', label: 'English' },
  { value: 'English (Australia)', label: 'English (Australia)' },
  { value: 'English (Canada)', label: 'English (Canada)' },
  { value: 'English (India)', label: 'English (India)' },
  { value: 'English (New Zealand)', label: 'English (New Zealand)' },
  { value: 'English (South Africa)', label: 'English (South Africa)' },
  { value: 'English (United Kingdom)', label: 'English (United Kingdom)' },
  { value: 'English (United States)', label: 'English (United States)' },
  { value: 'Esperanto', label: 'Esperanto - esperanto' },
  { value: 'Estonian', label: 'Estonian - eesti' },
  { value: 'Faroese', label: 'Faroese - føroyskt' },
  { value: 'Filipino', label: 'Filipino' },
  { value: 'Finnish', label: 'Finnish - suomi' },
  { value: 'French', label: 'French - français' },
  { value: 'French (Canada)', label: 'French (Canada) - français (Canada)' },
  { value: 'French (France)', label: 'French (France) - français (France)' },
  { value: 'French (Switzerland)', label: 'French (Switzerland) - français (Suisse)' },
  { value: 'Galician', label: 'Galician - galego' },
  { value: 'Georgian', label: 'Georgian - ქართული' },
  { value: 'German', label: 'German - Deutsch' },
  { value: 'German (Austria)', label: 'German (Austria) - Deutsch (Österreich)' },
  { value: 'German (Germany)', label: 'German (Germany) - Deutsch (Deutschland)' },
  { value: 'German (Liechtenstein)', label: 'German (Liechtenstein) - Deutsch (Liechtenstein)' },
  { value: 'German (Switzerland)', label: 'German (Switzerland) - Deutsch (Schweiz)' },
  { value: 'Greek', label: 'Greek - Ελληνικά' },
  { value: 'Guarani', label: 'Guarani' },
  { value: 'Gujarati', label: 'Gujarati - ગુજરાતી' },
  { value: 'Hausa', label: 'Hausa' },
  { value: 'Hawaiian', label: 'Hawaiian - ʻŌlelo Hawaiʻi' },
  { value: 'Hebrew', label: 'Hebrew - עברית' },
  { value: 'Hindi', label: 'Hindi - हिन्दी' },
  { value: 'Hungarian', label: 'Hungarian - magyar' },
  { value: 'Icelandic', label: 'Icelandic - íslenska' },
  { value: 'Indonesian', label: 'Indonesian - Indonesia' },
  { value: 'Interlingua', label: 'Interlingua' },
  { value: 'Irish', label: 'Irish - Gaeilge' },
  { value: 'Italian', label: 'Italian - italiano' },
  { value: 'Italian (Italy)', label: 'Italian (Italy) - italiano (Italia)' },
  { value: 'Italian (Switzerland)', label: 'Italian (Switzerland) - italiano (Svizzera)' },
  { value: 'Japanese', label: 'Japanese - 日本語' },
  { value: 'Kannada', label: 'Kannada - ಕನ್ನಡ' },
  { value: 'Kazakh', label: 'Kazakh - қазақ тілі' },
  { value: 'Khmer', label: 'Khmer - ខ្មែរ' },
  { value: 'Korean', label: 'Korean - 한국어' },
  { value: 'Kurdish', label: 'Kurdish - Kurdî' },
  { value: 'Kyrgyz', label: 'Kyrgyz - кыргызча' },
  { value: 'Lao', label: 'Lao - ລາວ' },
  { value: 'Latin', label: 'Latin' },
  { value: 'Latvian', label: 'Latvian - latviešu' },
  { value: 'Lingala', label: 'Lingala - lingála' },
  { value: 'Lithuanian', label: 'Lithuanian - lietuvių' },
  { value: 'Macedonian', label: 'Macedonian - македонски' },
  { value: 'Malay', label: 'Malay - Bahasa Melayu' },
  { value: 'Malayalam', label: 'Malayalam - മലയാളം' },
  { value: 'Maltese', label: 'Maltese - Malti' },
  { value: 'Marathi', label: 'Marathi - मराठी' },
  { value: 'Mongolian', label: 'Mongolian - монгол' },
  { value: 'Nepali', label: 'Nepali - नेपाली' },
  { value: 'Norwegian', label: 'Norwegian - norsk' },
  { value: 'Norwegian Bokmål', label: 'Norwegian Bokmål - norsk bokmål' },
  { value: 'Norwegian Nynorsk', label: 'Norwegian Nynorsk - nynorsk' },
  { value: 'Occitan', label: 'Occitan' },
  { value: 'Oriya', label: 'Oriya - ଓଡ଼ିଆ' },
  { value: 'Oromo', label: 'Oromo - Oromoo' },
  { value: 'Pashto', label: 'Pashto - پښتو' },
  { value: 'Persian', label: 'Persian - فارسی' },
  { value: 'Polish', label: 'Polish - polski' },
  { value: 'Portuguese', label: 'Portuguese - português' },
  { value: 'Portuguese (Brazil)', label: 'Portuguese (Brazil) - português (Brasil)' },
  { value: 'Portuguese (Portugal)', label: 'Portuguese (Portugal) - português (Portugal)' },
  { value: 'Punjabi', label: 'Punjabi - ਪੰਜਾਬੀ' },
  { value: 'Quechua', label: 'Quechua' },
  { value: 'Romanian', label: 'Romanian - română' },
  { value: 'Romanian (Moldova)', label: 'Romanian (Moldova) - română (Moldova)' },
  { value: 'Romansh', label: 'Romansh - rumantsch' },
  { value: 'Russian', label: 'Russian - русский' },
  { value: 'Scottish Gaelic', label: 'Scottish Gaelic' },
  { value: 'Serbian', label: 'Serbian - српски' },
  { value: 'Serbo', label: 'Serbo - Croatian' },
  { value: 'Shona', label: 'Shona - chiShona' },
  { value: 'Sindhi', label: 'Sindhi' },
  { value: 'Sinhala', label: 'Sinhala - සිංහල' },
  { value: 'Slovak', label: 'Slovak - slovenčina' },
  { value: 'Slovenian', label: 'Slovenian - slovenščina' },
  { value: 'Somali', label: 'Somali - Soomaali' },
  { value: 'Southern Sotho', label: 'Southern Sotho' },
  { value: 'Spanish', label: 'Spanish - español' },
  { value: 'Spanish (Argentina)', label: 'Spanish (Argentina) - español (Argentina)' },
  { value: '1Spanish (Latin America)', label: '1Spanish (Latin America) - español (Latinoamérica)' },
  { value: 'Spanish (Mexico)', label: 'Spanish (Mexico) - español (México)' },
  { value: 'Spanish (Spain)', label: 'Spanish (Spain) - español (España)' },
  { value: 'Spanish (United States)', label: 'Spanish (United States) - español (Estados Unidos)' },
  { value: 'Sundanese', label: 'Sundanese' },
  { value: 'Swahili', label: 'Swahili - Kiswahili' },
  { value: 'Swedish', label: 'Swedish - svenska' },
  { value: 'Tajik', label: 'Tajik - тоҷикӣ' },
  { value: 'Tamil', label: 'Tamil - தமிழ்' },
  { value: 'Tatar', label: 'Tatar' },
  { value: 'Telugu', label: 'Telugu - తెలుగు' },
  { value: 'Thai', label: 'Thai - ไทย' },
  { value: 'Tigrinya', label: 'Tigrinya - ትግርኛ' },
  { value: 'Tongan', label: 'Tongan - lea fakatonga' },
  { value: 'Turkish', label: 'Turkish - Türkçe' },
  { value: 'Turkmen', label: 'Turkmen' },
  { value: 'Twi', label: 'Twi' },
  { value: 'Ukrainian', label: 'Ukrainian - українська' },
  { value: 'Urdu', label: 'Urdu - اردو' },
  { value: 'Uyghur', label: 'Uyghur' },
  { value: 'Uzbek', label: 'Uzbek - o‘zbek' },
  { value: 'Vietnamese', label: 'Vietnamese - Tiếng Việt' },
  { value: 'Walloon', label: 'Walloon - wa' },
  { value: 'Welsh', label: 'Welsh - Cymraeg' },
  { value: 'Western Frisian', label: 'Western Frisian' },
  { value: 'Xhosa', label: 'Xhosa' },
  { value: 'Yiddish', label: 'Yiddish' },
  { value: 'Yoruba', label: 'Yoruba - Èdè Yorùbá' },
  { value: 'Zulu', label: 'Zulu - isiZulu' },
];

export const genderOption = [
  {
    value: '1',
    label: 'Nam',
  },
  {
    value: '0',
    label: 'Nữ',
  },
  {
    value: '3',
    label: 'Khác',
  },
];

export const statusBorrowOption = [
  {
    value: 0,
    label: 'Tất cả',
  },
  {
    value: 10,
    label: 'Chờ xác nhận',
  },
  {
    value: 20,
    label: 'Đang mượn',
  },
  {
    value: 30,
    label: 'Đã trả',
  },
  {
    value: 50,
    label: 'Hủy',
  },
  {
    value: 60,
    label: 'Mất sách (chưa xử lý)',
  },
  {
    value: 70,
    label: 'Mất sách (đã xử lý)',
  },
];

export const nationOption = [
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Aland Islands', label: 'Aland Islands' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'American Samoa', label: 'American Samoa' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Anguilla', label: 'Anguilla' },
  { value: 'Antarctica', label: 'Antarctica' },
  { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Aruba', label: 'Aruba' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bermuda', label: 'Bermuda' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bonaire, Sint Eustatius and Saba', label: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Bouvet Island', label: 'Bouvet Island' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'British Indian Ocean Territory', label: 'British Indian Ocean Territory' },
  { value: 'Brunei Darussalam', label: 'Brunei Darussalam' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Burkina Faso', label: 'Burkina Faso' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Cape Verde', label: 'Cape Verde' },
  { value: 'Cayman Islands', label: 'Cayman Islands' },
  { value: 'Central African Republic', label: 'Central African Republic' },
  { value: 'Chad', label: 'Chad' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Christmas Island', label: 'Christmas Island' },
  { value: 'Cocos (Keeling) Islands', label: 'Cocos (Keeling) Islands' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Comoros', label: 'Comoros' },
  { value: 'Congo', label: 'Congo' },
  { value: 'Congo, Democratic Republic of the Congo', label: 'Congo, Democratic Republic of the Congo' },
  { value: 'Cook Islands', label: 'Cook Islands' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: "Cote D'Ivoire", label: "Cote D'Ivoire" },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Curacao', label: 'Curacao' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
  { value: 'Eritrea', label: 'Eritrea' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Falkland Islands (Malvinas)', label: 'Falkland Islands (Malvinas)' },
  { value: 'Faroe Islands', label: 'Faroe Islands' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'French Guiana', label: 'French Guiana' },
  { value: 'French Polynesia', label: 'French Polynesia' },
  { value: 'French Southern Territories', label: 'French Southern Territories' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambia', label: 'Gambia' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Gibraltar', label: 'Gibraltar' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Greenland', label: 'Greenland' },
  { value: 'Grenada', label: 'Grenada' },
  { value: 'Guadeloupe', label: 'Guadeloupe' },
  { value: 'Guam', label: 'Guam' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guernsey', label: 'Guernsey' },
  { value: 'Guinea', label: 'Guinea' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Heard Island and Mcdonald Islands', label: 'Heard Island and Mcdonald Islands' },
  { value: 'Holy See (Vatican City State)', label: 'Holy See (Vatican City State)' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hong Kong', label: 'Hong Kong' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran, Islamic Republic of', label: 'Iran, Islamic Republic of' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Isle of Man', label: 'Isle of Man' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jersey', label: 'Jersey' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: "Korea, Democratic People's Republic of", label: "Korea, Democratic People's Republic of" },
  { value: 'Korea, Republic of', label: 'Korea, Republic of' },
  { value: 'Kosovo', label: 'Kosovo' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: "Lao People's Democratic Republic", label: "Lao People's Democratic Republic" },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libyan Arab Jamahiriya', label: 'Libyan Arab Jamahiriya' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Macao', label: 'Macao' },
  { value: 'Macedonia, the Former Yugoslav Republic of', label: 'Macedonia, the Former Yugoslav Republic of' },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
  { value: 'Martinique', label: 'Martinique' },
  { value: 'Mauritania', label: 'Mauritania' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mayotte', label: 'Mayotte' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Micronesia, Federated States of', label: 'Micronesia, Federated States of' },
  { value: 'Moldova, Republic of', label: 'Moldova, Republic of' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Montserrat', label: 'Montserrat' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Myanmar', label: 'Myanmar' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'Netherlands Antilles', label: 'Netherlands Antilles' },
  { value: 'New Caledonia', label: 'New Caledonia' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'Niue', label: 'Niue' },
  { value: 'Norfolk Island', label: 'Norfolk Island' },
  { value: 'Northern Mariana Islands', label: 'Northern Mariana Islands' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Palestinian Territory, Occupied', label: 'Palestinian Territory, Occupied' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Pitcairn', label: 'Pitcairn' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Puerto Rico', label: 'Puerto Rico' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Reunion', label: 'Reunion' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russian Federation', label: 'Russian Federation' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Saint Barthelemy', label: 'Saint Barthelemy' },
  { value: 'Saint Helena', label: 'Saint Helena' },
  { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia', label: 'Saint Lucia' },
  { value: 'Saint Martin', label: 'Saint Martin' },
  { value: 'Saint Pierre and Miquelon', label: 'Saint Pierre and Miquelon' },
  { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'San Marino', label: 'San Marino' },
  { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Serbia and Montenegro', label: 'Serbia and Montenegro' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Sint Maarten', label: 'Sint Maarten' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Somalia', label: 'Somalia' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Georgia and the South Sandwich Islands', label: 'South Georgia and the South Sandwich Islands' },
  { value: 'South Sudan', label: 'South Sudan' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sudan', label: 'Sudan' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Svalbard and Jan Mayen', label: 'Svalbard and Jan Mayen' },
  { value: 'Swaziland', label: 'Swaziland' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Syrian Arab Republic', label: 'Syrian Arab Republic' },
  { value: 'Taiwan, Province of China', label: 'Taiwan, Province of China' },
  { value: 'Tajikistan', label: 'Tajikistan' },
  { value: 'Tanzania, United Republic of', label: 'Tanzania, United Republic of' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Timor-Leste', label: 'Timor-Leste' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tokelau', label: 'Tokelau' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Turkmenistan', label: 'Turkmenistan' },
  { value: 'Turks and Caicos Islands', label: 'Turks and Caicos Islands' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'United States', label: 'United States' },
  { value: 'United States Minor Outlying Islands', label: 'United States Minor Outlying Islands' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Viet Nam', label: 'Viet Nam' },
  { value: 'Virgin Islands, British', label: 'Virgin Islands, British' },
  { value: 'Virgin Islands, U.s.', label: 'Virgin Islands, U.s.' },
  { value: 'Wallis and Futuna', label: 'Wallis and Futuna' },
  { value: 'Western Sahara', label: 'Western Sahara' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
];

export const sideBarMenu = [
  { title: 'Dashboard', src: CharFillIcon, route: '/dashboard' },
  { title: 'Tài khoản', src: UserIcon, route: '/user/all', gap: true },
  { title: 'Sách', src: CalenderIcon, route: '/book/all' },
  { title: 'Tác giả', src: UserIcon, route: '/author/all' },
  { title: 'Thể loại', src: CalenderIcon, route: '/category/all' },
  { title: 'Ngành', src: CalenderIcon, route: '/major/all' },
  { title: 'Sách mượn', src: CalenderIcon, route: '/borrow/all' },
  // { title: 'Setting', src: SettingIcon, route: '/setting/', gap: true },
];

export const tabBorrowBook = [
  {
    path: '/account/add/excel',
    displayText: 'Excel',
  },
  {
    path: '/account/add/text',
    displayText: 'Nhập liệu',
  },
];

export const classOption = [
  {
    label: 'CD21CT1',
    value: 'CD21CT1',
  },
  {
    label: 'CD21CT2',
    value: 'CD21CT2',
  },
  {
    label: 'CD21CT3',
    value: 'CD21CT3',
  },
  {
    label: 'CD21CT4',
    value: 'CD21CT4',
  },
  {
    label: 'CD21CT5',
    value: 'CD21CT5',
  },
  {
    label: 'CD21CT6',
    value: 'CD21CT6',
  },
  {
    label: 'CD21CT7',
    value: 'CD21CT7',
  },
  {
    label: 'CD21CT8',
    value: 'CD21CT8',
  },
];

export const borrowSearchOption = [
  {
    label: 'Mã sách mượn',
    value: 'borrowed_book_id',
  },
  {
    label: 'Tên sách',
    value: 'name',
  },
  {
    label: 'Mã số sinh viên',
    value: 'user_id',
  },
];

export const bookSearchOption = [
  {
    label: 'Mã sách',
    value: 'book_id',
  },
  {
    label: 'Tên sách',
    value: 'name',
  },
  {
    label: 'Kệ sách',
    value: 'bookshelf',
  },
];

export const categorySearchOption = [
  {
    label: 'Mã thể loại',
    value: 'category_id',
  },
  {
    label: 'Tên thể loại',
    value: 'name',
  },
];

export const majorSearchOption = [
  {
    label: 'Mã thể loại',
    value: 'industry_code_id',
  },
  {
    label: 'Tên thể loại',
    value: 'name',
  },
];

export const authorSearchOption = [
  {
    label: 'Mã tác giả',
    value: 'author_id',
  },
  {
    label: 'Tên tác giả',
    value: 'name',
  },
  {
    label: 'Kệ sách',
    value: 'bookshelf',
  },
  {
    label: 'Quốc gia',
    value: 'nation',
  },
];

export const accountSearchOption = [
  {
    label: 'Mã tài khoản',
    value: 'user_id',
  },
  {
    label: 'Tên tài khoản',
    value: 'name',
  },
  {
    label: 'Mã số sinh viên',
    value: 'mssv',
  },
  {
    label: 'Lớp',
    value: 'class',
  },
];
