CREATE TABLE public.user (
    user_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    isDeleted boolean DEFAULT false NOT NULL,
    name text NOT NULL,
    mssv text NOT NULL,
    avatar_uri text,
    password text NOT NULL,
    role smallint DEFAULT '0' :: smallint,
    phone_number text NOT NULL,
    email text,
    dob date,
    address text,
    gender smallint,
);