const CONFIGS = {
  //* URL_API
  REACT_APP_API_URL: process.env.REACT_APP_API_URL,

  // * Configs FireBase
  REACT_APP_API_KEY: process.env.REACT_APP_API_KEY,
  REACT_APP_AUTH_DOMAIN: process.env.REACT_APP_AUTH_DOMAIN,
  REACT_APP_DATA_BASE_URL: process.env.REACT_APP_DATA_BASE_URL,
  REACT_APP_PROJECT_ID: process.env.REACT_APP_PROJECT_ID,
  REACT_APP_STORAGE_BUCKET: process.env.REACT_APP_STORAGE_BUCKET,
  REACT_APP_MESSAGING_SENDER_ID: process.env.REACT_APP_MESSAGING_SENDER_ID,
  REACT_APP_APP_ID: process.env.REACT_APP_APP_ID,

  // * Key Facebook Login
  REACT_APP_KEY_FACEBOOK: process.env.REACT_APP_KEY_FACEBOOK,
  REACT_APP_KEY_FACEBOOK_TEST: process.env.REACT_APP_KEY_FACEBOOK_TEST,

  // * Key Google Login
  REACT_APP_KEY_GOOGLE: process.env.REACT_APP_KEY_GOOGLE,

  // * RecapCha Google
  REACT_APP_KEY_RECAPTCHA: process.env.REACT_APP_KEY_RECAPTCHA,
  REACT_APP_KEY_RECAPTCHA_V3: process.env.REACT_APP_KEY_RECAPTCHA_V3,

  //* Key Google Map
  REACT_APP_KEY_GOOGLE_MAP: process.env.REACT_APP_KEY_GOOGLE_MAP,
  REACT_APP_KEY_GOOGLE_MAP_MAIN: process.env.REACT_APP_KEY_GOOGLE_MAP_MAIN,
};
export default CONFIGS;
